name: Build Kivy App
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Check out code
      uses: actions/checkout@v2

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16

        
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: 19
        distribution: adopt
        
    - name: installing open jdk
      run: |
        sudo apt-get update
        sudo apt-get upgrade
        sudo apt-get install openjdk-8-jdk

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython
        sudo apt-get install -y \
          libgstreamer1.0 \
          android-sdk-platform-tools\
          python3-pip \
          build-essential \
          git \
          python3 \
          python3-dev \
          ffmpeg \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libportmidi-dev \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev \
          zlib1g-dev \
          gstreamer1.0-plugins-base \
          gstreamer1.0-plugins-good \
          libffi-dev \
          libssl-dev \
          libsqlite3-dev

        # Install Node.js 16
        curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
        sudo apt-get install -y nodejs
        $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "build-tools;30.0.3" "platforms;android-30" "extras;android;m2repository" "extras;google;m2repository"
        yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses
        sudo apt-get clean
    
    - name: Build the app
      run: |
        buildozer android debug
